# -*- coding: utf-8 -*-
"""
Created on Thu Apr 21 14:48:30 2016

@author: sunwhale
"""

DictCountry={
'UN':'US',\
'':"原始文件未列出",\
'A':'AE',\
'BENIN':'BJ',\
'CAMBODIA':'KH',\
'CAMEROON':'CM',\
'CAMEROUN':'CM',\
'CD':'CG',\
'CONGO':'CG',\
'GHANA':'GH',\
'HONG KONG':'HK',\
'IDDONESIA':'ID',\
'IDONESIA':'ID',\
'INDONESIA':'ID',\
'MALAYSIA':'MY',\
'MALAYSIAN':'MY',\
'MOZAMBIQUE':'MZ',\
'NIGERIA':'NG',\
'PHILIPPINES':'PH',\
'THAILAND':'TH',\
'VIETNAM':'VN',\
'印度尼西亚':'ID',\
'GAMBIA':'GM',\
'SS':'SS',\
'TOGO':'TG',\
'AD':'AD',\
'AE':'AE',\
'AF':'AF',\
'AG':'AG',\
'AI':'AI',\
'AL':'AL',\
'AM':'AM',\
'AO':'AO',\
'AQ':'AQ',\
'AR':'AR',\
'AT':'AT',\
'AU':'AU',\
'AW':'AW',\
'AZ':'AZ',\
'BA':'BA',\
'BB':'BB',\
'BD':'BD',\
'BE':'BE',\
'BF':'BF',\
'BG':'BG',\
'BH':'BH',\
'BI':'BI',\
'BJ':'BJ',\
'BM':'BM',\
'BN':'BN',\
'BO':'BO',\
'BR':'BR',\
'BS':'BS',\
'BT':'BT',\
'BV':'BV',\
'BW':'BW',\
'BY':'BY',\
'BY':'BY',\
'BZ':'BZ',\
'CA':'CA',\
'CC':'CC',\
'CF':'CF',\
'CG':'CG',\
'CH':'CH',\
'CI':'CI',\
'CK':'CK',\
'CL':'CL',\
'CM':'CM',\
'CN':'CN',\
'CO':'CO',\
'CR':'CR',\
'CU':'CU',\
'CV':'CV',\
'CX':'CX',\
'CY':'CY',\
'CZ':'CZ',\
'DE':'DE',\
'DJ':'DJ',\
'DK':'DK',\
'DM':'DM',\
'DO':'DO',\
'DZ':'DZ',\
'EC':'EC',\
'EC':'EC',\
'EE':'EE',\
'EG':'EG',\
'EH':'EH',\
'ES':'ES',\
'ET':'ET',\
'FI':'FI',\
'FJ':'FJ',\
'FK':'FK',\
'FM':'FM',\
'FR':'FR',\
'GA':'GA',\
'GB':'GB',\
'GD':'GD',\
'GE':'GE',\
'GF':'GF',\
'GH':'GH',\
'GI':'GI',\
'GL':'GL',\
'GM':'GM',\
'GN':'GN',\
'GP':'GP',\
'GQ':'GQ',\
'GR':'GR',\
'GT':'GT',\
'GU':'GU',\
'GW':'GW',\
'GY':'GY',\
'HK':'HK',\
'HN':'HN',\
'HR':'HR',\
'HT':'HT',\
'HU':'HU',\
'ID':'ID',\
'IE':'IE',\
'IL':'IL',\
'IN':'IN',\
'IO':'IO',\
'IQ':'IQ',\
'IR':'IR',\
'IS':'IS',\
'IT':'IT',\
'JM':'JM',\
'JO':'JO',\
'JP':'JP',\
'KE':'KE',\
'KG':'KG',\
'KH':'KH',\
'KI':'KI',\
'KM':'KM',\
'KP':'KP',\
'KR':'KR',\
'KW':'KW',\
'KY':'KY',\
'KZ':'KZ',\
'LA':'LA',\
'LB':'LB',\
'LC':'LC',\
'LI':'LI',\
'LK':'LK',\
'LR':'LR',\
'LS':'LS',\
'LT':'LT',\
'LU':'LU',\
'LV':'LV',\
'LY':'LY',\
'MA':'MA',\
'MC':'MC',\
'MD':'MD',\
'MG':'MG',\
'MH':'MH',\
'ML':'ML',\
'MM':'MM',\
'MN':'MN',\
'MO':'MO',\
'MP':'MP',\
'MR':'MR',\
'MS':'MS',\
'MT':'MT',\
'MU':'MU',\
'MV':'MV',\
'MW':'MW',\
'MX':'MX',\
'MY':'MY',\
'MZ':'MZ',\
'NA':'NA',\
'NC':'NC',\
'NE':'NE',\
'NF':'NF',\
'NG':'NG',\
'NI':'NI',\
'NL':'NL',\
'NO':'NO',\
'NP':'NP',\
'NR':'NR',\
'NT':'NT',\
'NU':'NU',\
'NZ':'NZ',\
'OM':'OM',\
'PA':'PA',\
'PE':'PE',\
'PF':'PF',\
'PG':'PG',\
'PH':'PH',\
'PK':'PK',\
'PL':'PL',\
'PN':'PN',\
'PR':'PR',\
'PT':'PT',\
'PW':'PW',\
'PY':'PY',\
'QA':'QA',\
'RO':'RO',\
'RU':'RU',\
'RW':'RW',\
'SA':'SA',\
'SB':'SB',\
'SC':'SC',\
'SD':'SD',\
'SE':'SE',\
'SG':'SG',\
'SH':'SH',\
'SI':'SI',\
'SK':'SK',\
'SL':'SL',\
'SM':'SM',\
'SN':'SN',\
'SO':'SO',\
'SR':'SR',\
'ST':'ST',\
'SU':'SU',\
'SV':'SV',\
'SY':'SY',\
'SZ':'SZ',\
'TC':'TC',\
'TD':'TD',\
'TF':'TF',\
'TG':'TG',\
'TH':'TH',\
'TJ':'TJ',\
'TK':'TK',\
'TM':'TM',\
'TN':'TN',\
'TO':'TO',\
'TP':'TP',\
'TR':'TR',\
'TT':'TT',\
'TV':'TV',\
'TW':'TW',\
'TZ':'TZ',\
'UA':'UA',\
'UG':'UG',\
'UK':'UK',\
'UM':'UM',\
'US':'US',\
'UY':'UY',\
'UZ':'UZ',\
'VA':'VA',\
'VE':'VE',\
'VG':'VG',\
'VI':'VI',\
'VN':'VN',\
'VU':'VU',\
'WS':'WS',\
'YE':'YE',\
'YU':'YU',\
'ZA':'ZA',\
'ZM':'ZM',\
'ZR':'ZR',\
'ZW':'ZW'
}

DictCountryToEnglish={
'AD':'Andorra',\
'AE':'United Arab Emirates',\
'AF':'Afghanistan',\
'AG':'Ntigua and Barbuda',\
'AI':'Angola',\
'AL':'Albania',\
'AM':'Armenia',\
'AO':'Angola',\
'AQ':'Antarctica',\
'AR':'Argentina',\
'AT':'Austria',\
'AU':'Australia',\
'AW':'Aruba',\
'AZ':'Azerbaijan',\
'BA':'Bosnia Hercegovina',\
'BB':'Barbados',\
'BD':'Bangladesh',\
'BE':'Belgium',\
'BF':'Burkina Faso',\
'BG':'Bulgaria',\
'BH':'Bahrain',\
'BI':'Burundi',\
'BJ':'Benin',\
'BM':'Bermuda',\
'BN':'Brunei Darussalam',\
'BO':'Bolivia',\
'BR':'Brazil',\
'BS':'Bahamas',\
'BT':'Bhutan',\
'BV':'Bouvet Island',\
'BW':'Botswana',\
'BY':'White Russia',\
'BY':'Byelorussian SSR',\
'BZ':'Belize',\
'CA':'Canada',\
'CC':'COCOS Islands',\
'CF':'The Central African Republic',\
'CG':'Congo',\
'CH':'Switzerland',\
'CI':'Lvory Coast',\
'CK':'Cook Island',\
'CL':'Chile',\
'CM':'Cameroon',\
'CN':'China',\
'CO':'Colombia',\
'CR':'Costa rica',\
'CU':'Cuba',\
'CV':'Cape Verde,Republic of',\
'CX':'Christmas Island',\
'CY':'Cyprus',\
'CZ':'Czech Republic',\
'DE':'Grmany',\
'DJ':'Djibouti',\
'DK':'Denmark',\
'DM':'Gominica',\
'DO':'Dominica',\
'DZ':'Algeria',\
'EC':'Ecuador',\
'EC':'Ecuador',\
'EE':'Estonia',\
'EG':'Egypt',\
'EH':'West Sahara',\
'ES':'Spain',\
'ET':'Ethiopia',\
'FI':'Finland',\
'FJ':'Fiji',\
'FK':'Falkland Islands',\
'FM':'Micronesia',\
'FR':'France',\
'GA':'Gabon',\
'GB':'United Kingdom',\
'GD':'Grenada',\
'GE':'Georgia',\
'GF':'French Guiana',\
'GH':'Ghana',\
'GI':'Gibraltar',\
'GL':'Greenland',\
'GM':'Gambia',\
'GN':'Guinea',\
'GP':'Guadeloupe',\
'GQ':'Equatorial Guinea',\
'GR':'Greece',\
'GT':'Guatemala',\
'GU':'Guam',\
'GW':'Guinea-Bissau',\
'GY':'Guyana',\
'HK':'Hong Kong',\
'HN':'Honduras',\
'HR':'Croatia',\
'HT':'Haiti',\
'HU':'Hungary',\
'ID':'Indonesia',\
'IE':'Ireland',\
'IL':'Israel',\
'IN':'India',\
'IO':'British Indian Ocean Territory',\
'IQ':'Iraq',\
'IR':'Iran',\
'IS':'Iceland',\
'IT':'Italy',\
'JM':'Jamaica',\
'JO':'Jordan',\
'JP':'Japan',\
'KE':'Kenya',\
'KG':'Kyrgyzstan',\
'KH':'Cambodia',\
'KI':'Kiribati',\
'KM':'Comoros',\
'KP':'North Korea',\
'KR':'Korea',\
'KW':'kuwait',\
'KY':'Cayman Islands',\
'KZ':'Kazakstan',\
'LA':'Laos',\
'LB':'Lebanon',\
'LC':'St. Lucia',\
'LI':'Liechtenstein',\
'LK':'Sri Lanka',\
'LR':'Liberia',\
'LS':'Lesotho',\
'LT':'Lithuania',\
'LU':'Luxembourg',\
'LV':'Latvia',\
'LY':'Libya',\
'MA':'Morocco',\
'MC':'Monaco',\
'MD':'Moldova,Republic of',\
'MG':'Malagasy',\
'MH':'Marshall Islands',\
'ML':'Mali',\
'MM':'Burma',\
'MN':'Mongolia',\
'MO':'Macao',\
'MP':'Northern Nariana Islands',\
'MR':'Mauritania',\
'MS':'Montserrat',\
'MT':'Malta',\
'MU':'Mauritius',\
'MV':'Maldives',\
'MW':'Malawi',\
'MX':'Mexico',\
'MY':'Malaysia',\
'MZ':'Mozambique',\
'NA':'Namibia',\
'NC':'New Caledonia',\
'NE':'Niger',\
'NF':'Norfolk Island',\
'NG':'Nigeria',\
'NI':'Nicaragua',\
'NL':'Netherlands',\
'NO':'Norway',\
'NP':'Nepal',\
'NR':'Naura',\
'NT':'Neutral Zone',\
'NU':'Niue',\
'NZ':'New Zealand',\
'OM':'Oman',\
'PA':'Panama',\
'PE':'Peru',\
'PF':'French Polynesia',\
'PG':'Papua Territory of',\
'PH':'Philippines',\
'PK':'Pakistan',\
'PL':'Poland',\
'PN':'Pitcairn Islands',\
'PR':'Puerto Rico',\
'PT':'Portugal',\
'PW':'Palau',\
'PY':'Paraguay',\
'QA':'Qatar',\
'RO':'Romania',\
'RU':'Russia',\
'RW':'Rwanda',\
'SA':'Saudi Arabia',\
'SB':'Solomon Islands',\
'SC':'Seychelles',\
'SD':'Sudan',\
'SE':'Sweden',\
'SG':'Singapore',\
'SH':'St.Helena',\
'SI':'Slovene',\
'SK':'Slovakia',\
'SL':'Sierra leone',\
'SM':'San Marino',\
'SN':'Senegal',\
'SO':'Somali',\
'SR':'Surinam',\
'SS':'South Sudan',\
'ST':'Sao Tome and Principe',\
'SU':'USSR(formerly)',\
'SV':'El Salvador',\
'SY':'Syria',\
'SZ':'Swaziland',\
'TC':'Turks and Caicos Islands',\
'TD':'Chad',\
'TF':'French Southern Territoties',\
'TG':'Togo',\
'TH':'Thailand',\
'TJ':'Tsjikistan',\
'TK':'Tokela',\
'TM':'Turkomanstan',\
'TN':'Tunisia',\
'TO':'Tonga',\
'TP':'East Timor',\
'TR':'Turkey',\
'TT':'Trinidad and Tobago',\
'TV':'Tuvalu',\
'TW':'Taiwan',\
'TZ':'Tanzania',\
'UA':'Ukiain',\
'UG':'Uganda',\
'UK':'England',\
'UM':'US Minor Outlying Islands',\
'US':'America',\
'UY':'uruguay',\
'UZ':'Uzbekstan',\
'VA':'Vatican',\
'VE':'Venezuela',\
'VG':'Virgin Islands(British)',\
'VI':'Vigin Islands(U.S.)',\
'VN':'Vietnam',\
'VU':'Vanuatu',\
'WS':'Western Samoa',\
'YE':'Yemen',\
'YU':'Yugoslavia',\
'ZA':'South Africa',\
'ZM':'Zambia',\
'ZR':'Zaire',\
'ZW':'Zimbabwe',\
'原始文件未列出':'原始文件未列出',\
}

DictCountryToChinese={
'AD':'安道尔',\
'AE':'阿联酋',\
'AF':'阿富汗',\
'AG':'安提瓜和巴布达',\
'AI':'安圭拉',\
'AL':'阿尔巴尼亚',\
'AM':'亚美尼亚',\
'AO':'安哥拉',\
'AQ':'南极洲',\
'AR':'阿根廷',\
'AT':'奥地利',\
'AU':'澳大利亚',\
'AW':'阿鲁巴',\
'AZ':'阿塞拜疆',\
'BA':'波黑',\
'BB':'巴巴多斯',\
'BD':'孟加拉',\
'BE':'比利时',\
'BF':'布其纳法索',\
'BG':'保加利亚',\
'BH':'巴林',\
'BI':'布隆迪',\
'BJ':'贝宁',\
'BM':'百慕大',\
'BN':'文莱',\
'BO':'玻利维亚',\
'BR':'巴西',\
'BS':'巴哈马',\
'BT':'不丹',\
'BV':'布维岛',\
'BW':'博茨瓦纳',\
'BY':'白俄罗斯',\
'BY':'白俄罗斯',\
'BZ':'伯利兹',\
'CA':'加拿大',\
'CC':'可可岛',\
'CF':'中非共和国',\
'CG':'刚果',\
'CH':'瑞士',\
'CI':'象牙海岸',\
'CK':'库克群岛',\
'CL':'智利',\
'CM':'喀麦隆',\
'CN':'中国',\
'CO':'哥伦比亚',\
'CR':'哥斯达黎加',\
'CU':'古巴',\
'CV':'佛得角',\
'CX':'圣诞岛',\
'CY':'塞浦路斯',\
'CZ':'捷克共和国',\
'DE':'德国',\
'DJ':'吉布提',\
'DK':'丹麦',\
'DM':'多明哥',\
'DO':'多米尼加',\
'DZ':'阿尔及利亚',\
'EC':'厄瓜多尔',\
'EC':'厄瓜多尔',\
'EE':'爱沙尼亚',\
'EG':'埃及',\
'EH':'西撒哈拉',\
'ES':'西班牙',\
'ET':'埃塞俄比亚',\
'FI':'芬兰',\
'FJ':'斐济',\
'FK':'福克兰群岛',\
'FM':'密克罗尼西亚',\
'FR':'法国',\
'GA':'加蓬',\
'GB':'英国',\
'GD':'格林纳达',\
'GE':'格鲁吉亚',\
'GF':'法属圭亚那',\
'GH':'加纳',\
'GI':'直布罗陀',\
'GL':'格陵兰',\
'GM':'冈比亚',\
'GN':'几内亚',\
'GP':'瓜德罗普',\
'GQ':'赤道几内亚',\
'GR':'希腊',\
'GT':'危地马拉',\
'GU':'关岛',\
'GW':'几内亚比绍',\
'GY':'圭亚那',\
'HK':'中国香港',\
'HN':'洪都拉斯',\
'HR':'克罗地亚',\
'HT':'海地',\
'HU':'匈牙利',\
'ID':'印度尼西亚',\
'IE':'爱尔兰',\
'IL':'以色列',\
'IN':'印度',\
'IO':'英联邦的印度洋领域',\
'IQ':'伊拉克',\
'IR':'伊朗',\
'IS':'冰岛',\
'IT':'意大利',\
'JM':'牙买加',\
'JO':'约旦',\
'JP':'日本',\
'KE':'肯尼亚',\
'KG':'吉尔吉斯斯坦',\
'KH':'柬埔寨',\
'KI':'基里巴斯',\
'KM':'科摩罗',\
'KP':'朝鲜',\
'KR':'韩国',\
'KW':'科威特',\
'KY':'开曼群岛',\
'KZ':'哈萨克斯坦',\
'LA':'老挝',\
'LB':'黎巴嫩',\
'LC':'圣卢西亚',\
'LI':'列支敦士登',\
'LK':'斯里兰卡',\
'LR':'利比里亚',\
'LS':'莱索托',\
'LT':'立陶宛',\
'LU':'卢森堡',\
'LV':'拉托维亚',\
'LY':'利比亚',\
'MA':'摩洛哥',\
'MC':'摩纳哥',\
'MD':'摩尔多瓦',\
'MG':'马达加斯加',\
'MH':'马绍尔群岛',\
'ML':'马里',\
'MM':'缅甸',\
'MN':'蒙古',\
'MO':'中国澳门',\
'MP':'北马里亚纳群岛',\
'MR':'毛里塔尼亚',\
'MS':'蒙特色拉特岛（位于美洲）',\
'MT':'马尔他',\
'MU':'毛里求斯',\
'MV':'马尔代夫',\
'MW':'马拉维',\
'MX':'墨西哥',\
'MY':'马来西亚',\
'MZ':'莫桑比克',\
'NA':'纳米比亚',\
'NC':'新喀里多尼亚',\
'NE':'尼日尔',\
'NF':'诺福克岛（澳大利亚位于西南太平洋的岛屿）',\
'NG':'尼日利亚',\
'NI':'尼加拉瓜',\
'NL':'荷兰',\
'NO':'挪威',\
'NP':'尼泊尔',\
'NR':'瑙鲁',\
'NT':'蒙塞拉特岛',\
'NU':'纽埃',\
'NZ':'新西兰',\
'OM':'阿曼',\
'PA':'巴拿马',\
'PE':'秘鲁',\
'PF':'法属玻里尼西亚',\
'PG':'巴布亚新几内亚',\
'PH':'菲律宾',\
'PK':'巴基斯坦',\
'PL':'波兰',\
'PN':'皮特开恩群岛',\
'PR':'波多黎各（美）',\
'PT':'葡萄牙',\
'PW':'帕劳',\
'PY':'巴拉圭',\
'QA':'卡塔尔',\
'RO':'罗马尼亚',\
'RU':'俄罗斯联邦',\
'RW':'卢旺达',\
'SA':'沙特阿拉伯',\
'SB':'所罗门群岛',\
'SC':'塞舌尔',\
'SD':'苏丹',\
'SE':'瑞典',\
'SG':'新加坡',\
'SH':'圣赫勒那',\
'SI':'斯洛文尼亚',\
'SK':'斯洛伐克',\
'SL':'塞拉利昂',\
'SM':'圣马力诺',\
'SN':'塞内加尔',\
'SO':'索马里',\
'SR':'苏里南',\
'SS':'南苏丹',\
'ST':'圣多美与普林西比',\
'SU':'苏联(前)',\
'SV':'萨尔瓦多',\
'SY':'叙利亚',\
'SZ':'斯威士兰',\
'TC':'特克斯和凯科斯群岛',\
'TD':'乍得',\
'TF':'法属南方领土',\
'TG':'多哥',\
'TH':'泰国',\
'TJ':'塔吉克斯坦',\
'TK':'托克劳',\
'TM':'土库曼斯坦',\
'TN':'突尼斯',\
'TO':'汤加',\
'TP':'东帝',\
'TR':'土尔其',\
'TT':'特立尼达和多巴哥',\
'TV':'图瓦卢　　　　',\
'TW':'中国台湾',\
'TZ':'坦桑尼亚',\
'UA':'乌克兰',\
'UG':'乌干达',\
'UK':'英国',\
'UM':'美国边远小岛',\
'US':'美国',\
'UY':'乌拉圭',\
'UZ':'乌兹别克斯坦',\
'VA':'梵蒂冈',\
'VE':'委内瑞拉',\
'VG':'不列颠岛(英)',\
'VI':'不列颠岛(美)',\
'VN':'越南',\
'VU':'瓦努阿图',\
'WS':'西萨摩亚',\
'YE':'也门',\
'YU':'南斯拉夫',\
'ZA':'南非',\
'ZM':'赞比亚',\
'ZR':'扎伊尔',\
'ZW':'津巴布韦',\
'原始文件未列出':'原始文件未列出',\
}